---

- name: Configuring ntp
  template: >
    src=etc-ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644
  notify: restart ntp
  tags:
    - system
    - ntp
    - config

- name: Configuring service
  service: >
    name=ntp
    state={{ ntp_service_state }}
    enabled={{ ntp_service_enabled }}
  tags:
    - system
    - ntp
    - config
